# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-31 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Adeployment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploylist',
            name='date',
        ),
        migrations.AddField(
            model_name='logsfield',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
