# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-31 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adeployment', '0003_auto_20180831_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogsField',
            new_name='Logs',
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name': '\u7cfb\u7edf\u65e5\u5fd7', 'verbose_name_plural': '\u7cfb\u7edf\u65e5\u5fd7'},
        ),
    ]
