# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-31 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adeployment', '0004_auto_20180831_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetype',
            options={'verbose_name': '\u6a21\u677f\u7c7b\u578b', 'verbose_name_plural': '\u6a21\u677f\u7c7b\u578b'},
        ),
    ]
